-- Idébanken — skema for det offentlige idéboard + admin
--
-- Tre begreber holdes adskilt med vilje:
--   review_state : hvor idéen er i moderationen (pending -> approved / discarded)
--   status       : hvilken kolonne den ligger i på brættet (kun relevant når approved)
--   hidden       : admin har taget en godkendt idé af brættet igen
-- Kun (review_state = 'approved' and hidden = false) er synligt for offentligheden.

create type public.idea_status as enum (
  'nye', 'vurdering', 'planlagt', 'udvikling', 'test', 'udgivet', 'afvist'
);

create type public.review_state as enum ('pending', 'approved', 'discarded');

-- Indsendere er anonyme. visitor_key er et tilfældigt id fra browserens
-- localStorage — det bruges til "én stemme pr. besøgende" og til rate limiting,
-- og er aldrig læsbart for offentligheden (se column grants nederst).

create table public.ideas (
  id            bigint generated by default as identity primary key,
  title         text not null check (char_length(btrim(title)) between 3 and 160),
  body          text not null check (char_length(btrim(body)) between 20 and 8000),
  category      text not null,
  importance    text not null,
  author        text not null default 'Anonym bruger' check (char_length(author) <= 60),
  status        public.idea_status not null default 'nye',
  review_state  public.review_state not null default 'pending',
  hidden        boolean not null default false,
  official_reply text not null default '',
  tags          text[] not null default '{}',
  -- up_count/down_count vedligeholdes af trigger og er base_* plus rigtige stemmer.
  -- base_* findes kun for at eksempelindholdet kan starte med et tal; for alt
  -- indsendt gennem sitet er de 0.
  base_up       integer not null default 0,
  base_down     integer not null default 0,
  up_count      integer not null default 0,
  down_count    integer not null default 0,
  comment_count integer not null default 0,
  merged_into   bigint references public.ideas (id) on delete set null,
  visitor_key   text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index ideas_board_idx on public.ideas (status, created_at desc)
  where review_state = 'approved' and hidden = false;
create index ideas_review_idx on public.ideas (review_state, created_at desc);
create index ideas_visitor_idx on public.ideas (visitor_key, created_at desc);

create table public.comments (
  id          bigint generated by default as identity primary key,
  idea_id     bigint not null references public.ideas (id) on delete cascade,
  author      text not null default 'Anonym' check (char_length(author) <= 60),
  body        text not null check (char_length(btrim(body)) between 1 and 2000),
  hidden      boolean not null default false,
  visitor_key text,
  created_at  timestamptz not null default now()
);

create index comments_idea_idx on public.comments (idea_id, created_at);
create index comments_visitor_idx on public.comments (visitor_key, created_at desc);

-- Stemmer er kun tilgængelige gennem RPC'erne nedenfor, aldrig direkte.
create table public.votes (
  idea_id     bigint not null references public.ideas (id) on delete cascade,
  visitor_key text not null,
  value       smallint not null check (value in (-1, 1)),
  created_at  timestamptz not null default now(),
  primary key (idea_id, visitor_key)
);

create table public.board_settings (
  id               integer primary key default 1 check (id = 1),
  require_approval boolean not null default true,
  allow_dislike    boolean not null default true,
  updated_at       timestamptz not null default now()
);

insert into public.board_settings (id) values (1);

-- E-mail-allowlist. At kunne logge ind er ikke nok — man skal stå her.
create table public.admins (
  email      text primary key,
  created_at timestamptz not null default now()
);


-- ---------------------------------------------------------------- funktioner

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admins
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger ideas_touch_updated_at
  before update on public.ideas
  for each row execute function public.touch_updated_at();

-- Tællerne holdes opdateret i databasen, så brættet kan læses med ét kald.
create or replace function public.sync_vote_counts()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target bigint := coalesce(new.idea_id, old.idea_id);
begin
  update public.ideas i
     set up_count   = i.base_up
                    + (select count(*) from public.votes v where v.idea_id = target and v.value = 1),
         down_count = i.base_down
                    + (select count(*) from public.votes v where v.idea_id = target and v.value = -1)
   where i.id = target;
  return null;
end;
$$;

create trigger votes_sync_counts
  after insert or update or delete on public.votes
  for each row execute function public.sync_vote_counts();

create or replace function public.sync_comment_count()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target bigint := coalesce(new.idea_id, old.idea_id);
begin
  update public.ideas i
     set comment_count = (
           select count(*) from public.comments c
            where c.idea_id = target and c.hidden = false
         )
   where i.id = target;
  return null;
end;
$$;

create trigger comments_sync_count
  after insert or update or delete on public.comments
  for each row execute function public.sync_comment_count();


-- ---------------------------------------------------------------------- RPC
-- Alt hvad en anonym besøgende kan skrive går gennem disse tre funktioner, så
-- validering og rate limiting sker i databasen og ikke kun i browseren.

create or replace function public.submit_idea(
  p_title       text,
  p_body        text,
  p_category    text,
  p_importance  text,
  p_author      text,
  p_visitor_key text,
  p_trap        text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_require_approval boolean;
  v_recent integer;
  v_id bigint;
begin
  -- Honeypot: feltet er skjult for mennesker, så udfyldt = bot.
  if btrim(coalesce(p_trap, '')) <> '' then
    raise exception 'Kunne ikke sende idéen.' using errcode = 'check_violation';
  end if;

  if coalesce(btrim(p_visitor_key), '') = '' then
    raise exception 'Mangler besøgs-id.' using errcode = 'check_violation';
  end if;

  if char_length(btrim(coalesce(p_title, ''))) < 3 then
    raise exception 'Skriv en titel på mindst 3 tegn.' using errcode = 'check_violation';
  end if;

  if char_length(btrim(coalesce(p_body, ''))) < 20 then
    raise exception 'Skriv mindst et par linjers beskrivelse.' using errcode = 'check_violation';
  end if;

  select count(*) into v_recent
    from public.ideas
   where visitor_key = p_visitor_key
     and created_at > now() - interval '1 hour';

  if v_recent >= 5 then
    raise exception 'Du har sendt mange idéer på kort tid. Prøv igen om lidt.'
      using errcode = 'check_violation';
  end if;

  select require_approval into v_require_approval from public.board_settings where id = 1;

  insert into public.ideas (title, body, category, importance, author, status, review_state, visitor_key)
  values (
    btrim(p_title),
    btrim(p_body),
    p_category,
    p_importance,
    coalesce(nullif(btrim(coalesce(p_author, '')), ''), 'Anonym bruger'),
    'nye',
    (case when v_require_approval then 'pending' else 'approved' end)::public.review_state,
    p_visitor_key
  )
  returning id into v_id;

  -- Man stemmer for sin egen idé, som i prototypen.
  insert into public.votes (idea_id, visitor_key, value) values (v_id, p_visitor_key, 1);

  return v_id;
end;
$$;

-- p_value er integer og ikke smallint med vilje: så rammer et almindeligt tal
-- fra en klient signaturen uden at skulle castes først.
create or replace function public.cast_vote(
  p_idea_id     bigint,
  p_visitor_key text,
  p_value       integer
)
returns table (up_count integer, down_count integer, my_vote integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing smallint;
  v_allow_dislike boolean;
begin
  if coalesce(btrim(p_visitor_key), '') = '' then
    raise exception 'Mangler besøgs-id.' using errcode = 'check_violation';
  end if;

  if p_value not in (-1, 1) then
    raise exception 'Ugyldig stemme.' using errcode = 'check_violation';
  end if;

  select allow_dislike into v_allow_dislike from public.board_settings where id = 1;
  if p_value = -1 and not v_allow_dislike then
    raise exception 'Der kan ikke stemmes imod.' using errcode = 'check_violation';
  end if;

  -- Kun idéer der faktisk er på brættet kan modtage stemmer.
  if not exists (
    select 1 from public.ideas
     where id = p_idea_id and review_state = 'approved' and hidden = false
  ) then
    raise exception 'Idéen findes ikke.' using errcode = 'no_data_found';
  end if;

  select value into v_existing
    from public.votes
   where idea_id = p_idea_id and visitor_key = p_visitor_key;

  if v_existing is null then
    insert into public.votes (idea_id, visitor_key, value)
    values (p_idea_id, p_visitor_key, p_value::smallint);
  elsif v_existing = p_value then
    delete from public.votes where idea_id = p_idea_id and visitor_key = p_visitor_key;
  else
    update public.votes set value = p_value::smallint
     where idea_id = p_idea_id and visitor_key = p_visitor_key;
  end if;

  return query
    select i.up_count,
           i.down_count,
           coalesce((select v.value from public.votes v
                      where v.idea_id = p_idea_id and v.visitor_key = p_visitor_key), 0::smallint)::integer
      from public.ideas i where i.id = p_idea_id;
end;
$$;

create or replace function public.add_comment(
  p_idea_id     bigint,
  p_visitor_key text,
  p_body        text,
  p_author      text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_recent integer;
  v_id bigint;
begin
  if coalesce(btrim(p_visitor_key), '') = '' then
    raise exception 'Mangler besøgs-id.' using errcode = 'check_violation';
  end if;

  if char_length(btrim(coalesce(p_body, ''))) = 0 then
    raise exception 'Skriv en kommentar først.' using errcode = 'check_violation';
  end if;

  if not exists (
    select 1 from public.ideas
     where id = p_idea_id and review_state = 'approved' and hidden = false
  ) then
    raise exception 'Idéen findes ikke.' using errcode = 'no_data_found';
  end if;

  select count(*) into v_recent
    from public.comments
   where visitor_key = p_visitor_key
     and created_at > now() - interval '10 minutes';

  if v_recent >= 10 then
    raise exception 'Du har skrevet mange kommentarer på kort tid. Prøv igen om lidt.'
      using errcode = 'check_violation';
  end if;

  insert into public.comments (idea_id, author, body, visitor_key)
  values (
    p_idea_id,
    coalesce(nullif(btrim(coalesce(p_author, '')), ''), 'Anonym'),
    btrim(p_body),
    p_visitor_key
  )
  returning id into v_id;

  return v_id;
end;
$$;

-- Den besøgendes egne stemmer, så knapperne kan vises rigtigt efter reload.
create or replace function public.my_votes(p_visitor_key text)
returns table (idea_id bigint, value integer)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select v.idea_id, v.value::integer
    from public.votes v
   where v.visitor_key = p_visitor_key;
$$;


-- ----------------------------------------------------------------- RLS / grants

alter table public.ideas          enable row level security;
alter table public.comments       enable row level security;
alter table public.votes          enable row level security;
alter table public.board_settings enable row level security;
alter table public.admins         enable row level security;

-- Offentligheden ser kun godkendte, ikke-skjulte idéer.
create policy ideas_public_read on public.ideas
  for select to anon, authenticated
  using (review_state = 'approved' and hidden = false);

create policy ideas_admin_all on public.ideas
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy comments_public_read on public.comments
  for select to anon, authenticated
  using (
    hidden = false
    and exists (
      select 1 from public.ideas i
       where i.id = comments.idea_id and i.review_state = 'approved' and i.hidden = false
    )
  );

create policy comments_admin_all on public.comments
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Ingen direkte adgang til votes; kun gennem RPC.
create policy votes_admin_read on public.votes
  for select to authenticated
  using (public.is_admin());

create policy settings_public_read on public.board_settings
  for select to anon, authenticated using (true);

create policy settings_admin_write on public.board_settings
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy admins_admin_read on public.admins
  for select to authenticated
  using (public.is_admin());

-- Tabelrettigheder: anonyme brugere må læse, men aldrig skrive direkte —
-- alle offentlige skrivninger går gennem RPC'erne ovenfor.
revoke all on public.ideas, public.comments, public.votes, public.board_settings, public.admins
  from anon, authenticated;

-- visitor_key er bevidst ikke med i listen: anonymitet er hele pointen.
grant select (
  id, title, body, category, importance, author, status, review_state, hidden,
  official_reply, tags, up_count, down_count, comment_count, merged_into,
  created_at, updated_at
) on public.ideas to anon, authenticated;

grant select (id, idea_id, author, body, hidden, created_at)
  on public.comments to anon, authenticated;

grant select on public.board_settings to anon, authenticated;

-- Admin arbejder som authenticated og er derudover afgrænset af RLS.
-- Bemærk at der ikke gives select på tabelniveau her: så ville en hvilken som
-- helst indlogget bruger kunne læse visitor_key. Læseadgangen er og bliver
-- kolonnelisten ovenfor.
grant insert, update, delete on public.ideas, public.comments to authenticated;
grant insert, update on public.board_settings to authenticated;
grant select on public.votes, public.admins to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.submit_idea(text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.cast_vote(bigint, text, integer) to anon, authenticated;
grant execute on function public.add_comment(bigint, text, text, text) to anon, authenticated;
grant execute on function public.my_votes(text) to anon, authenticated;
grant execute on function public.is_admin() to authenticated;
